project:
  type: website
  output-dir: docs

website:
  title: "tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: vectors_visual.qmd
      - href: Matrix.qmd
      - href: List.qmd
      - href: DataFrame_manipulations.qmd
      - href: factors_v2.qmd
      - href: dplyr.qmd
      - href: ReadingExternalDataFiles.qmd
      - href: Sas_R_comparisons.qmd
      - href: SQL_and_R.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

